### ISSUE TITLE
TypeError running tf.reshape on tf version 2.6.0

### ISSUE THREAD

**Issue by alstonda2016** [DoDuy/YOLOv4-to-CoreML#1]
boxes = tf.reshape(pred_bbox[:, :, 0:4], (-1, 4))
scores = tf.reshape(pred_bbox[:, :, 4:], (-1, 1))

consistently bring the error:
 
TypeError: list indices must be integers or slices, not tuple

**Comment by DoDuy** [comment]
@alstonda2016 
Please try tensorflow version 2.3.1 like my [requirements.txt](https://github.com/DoDuy/YOLOv4-to-CoreML/blob/main/requirements.txt) file

For IOS version from 15.0 we need split yolov4 model to 2 models (checkout notebook [Convert YOLOv4 Keras model to CoreML model For IOS15.ipynb](https://github.com/DoDuy/YOLOv4-to-CoreML/blob/main/Convert%20YOLOv4%20Keras%20model%20to%20CoreML%20model%20For%20IOS15.ipynb)), 
With the old notebook, when the model runs on IOS 15, this model will crash in some layers, because I don't want to change the architecture of YOLOv4, I decided to split the original model into 2 models at the layer before crashing.

Check out my split YOLOv4 models' results [AISudokuSolverApp](https://apps.apple.com/us/app/ai-sudoku-solver/id1553612098)

**Comment by alstonda2016** [comment]
This is awesome!!!! Thank you so much. 

Since the model is split now, does that mean this approach is incompatible with Apple's vision framework?

**Comment by DoDuy** [comment]
> Since the model is split now, does that mean this approach is incompatible with Apple's vision framework?

Split models work well with the CoreML framework

For my AISudokuSolver App, the yolov4 model is divided into 2 models called model 1 and model 2. When inference a new image, the image will run through model 1 then model 2
- Model 1: the image will always run pass-through model 1. 
This is an example of model 1's output
```
{'scores_max': array([0.96970564], dtype=float32),
 'class_boxes': array([[[ 11.9652195,  11.169098 , 245.27606  , 125.710144 ],
         [ 12.665116 ,  11.534476 , 221.87701  , 213.03012  ],
         [ 13.338507 ,   5.43204  , 221.44768  , 298.49866  ],
         ...,
         [296.9596   , 295.27176  , 332.6926   , 189.10931  ],
         [298.76837  , 302.72177  , 246.22118  , 333.7491   ],
         [298.46613  , 298.55136  , 313.58218  , 347.40826  ]]],
       dtype=float32),
 'pred_conf': array([[[2.0864643e-07],
         [5.9388549e-07],
         [1.8987319e-06],
         ...,
         [4.8263502e-08],
         [1.1795822e-07],
         [1.3884674e-07]]], dtype=float32)}
```
Model 2: Check model 1's output, if 'scores_max' >= confident_threshold, you can run model 2, and it will return you bounding boxes of objects. If 'scores_max' < confident_threshold, don't run model 2 because of the app crashing, so your image has no object

**Comment by alstonda2016** [comment]
Awesome, thanks so much! And does this bug with layers crashing also extend to testing  detect.py with the pb files made using the version of tensorflow-yolov4-tflite that you forked? I was able to generate the files but am getting:

Index out of range using input dim 0; input has only 0 dims [Op:StridedSlice] name: strided_slice/

when detect.py works normally in the version by hunglc007

**Comment by DoDuy** [comment]
I only modified save_model.py and core/yolov4.py files, so my tensorflow-yolov4-tflite only support running save_model.py to export .h5 file, my tensorflow-yolov4-tflite doesn't support detect.py so don't worry when run detect.py but got an error

For my  AISudokuSolver project, I execute the following command
```
python save_model.py --weights yolov4-tiny-custom-S4.2_last.weights --output yolov4-tiny4.2.1-320.h5 --input_size 320 --model yolov4 --tiny
```

**Comment by alstonda2016** [comment]
Got it, and is the output for the coordinates:

Boxes × [x, y, width, height] (relative to image size)

I'm having issues understanding how to convert the output to bounding box coordinates

**Comment by DoDuy** [comment]
@alstonda2016 

Output of model 2 for coordinates: out_dict['coordinates'] = [[x_min_scale, y_min_scale, x_max_scale, y_max_scale], ...]
with 0 <= x_min_scale, y_min_scale, x_max_scale, y_max_scale <= 1

You can convert to coordinates to coordinates of original image by multiplying the out_dict['coordinates'] by the image size

This is my example for image size = 320x320
![image](https://user-images.githubusercontent.com/7414333/144347165-39e5a934-9337-4ad4-b4f5-a411c8cc0ee6.png)

**Comment by alstonda2016** [comment]
I see, so it looks like I was setting the coordinates correctly but the issue is that the coordinates are outputting values greater than 1 for x_max_scale. Is there a way around this?

**Comment by DoDuy** [comment]
Try this: x_max_scale = min(1, max( 0, x_max_scale ))

**Comment by alstonda2016** [comment]
Thanks!
